### ISSUE TITLE
Support per source set configurations

### ISSUE THREAD

**Issue by Meijuh** [openrewrite/rewrite-gradle-plugin#194]
If I'm correct, the Gradle plugin currently does not support per source set configurations. This means there can only be one set of recipes for all source sets.
It would be useful to specify a set of recipes per source set, with defaults for the `main` and `test` source set. What I would like to see is something like the following.

```groovy
rewrite {
    activeStyle "org.openrewrite.java.GoogleJavaFormat"
}

rewriteMain {
  activeRecipe "recipe.A"
}

rewriteTest {
  activeRecipe "recipe.B"
}
```

A practical use case is removing a particular set of annotations in the main source set, while removing a different set of annotations in the test source set.

**Comment by shanman190** [comment]
@Meijuh, you can achieve this presently through the use of an applicability test from `rewrite` proper. So assuming that `recipe.A` and `recipe.B` modify the components with respect to the desired main vs test trait that you describe, you would then compose them in another recipe like below:

```
---
type: specs.openrewrite.org/v1beta/recipe
name: com.example.MigrateMainAnnotations
displayName: Apply the main annotation migrations
description: Applies the main annotation migrations.
applicability:
  anySource:
    - org.openrewrite.java.search.HasSourceSet:
        sourceSet: "main"
recipeList:
  - recipe.A
---
type: specs.openrewrite.org/v1beta/recipe
name: com.example.MigrateTestAnnotations
displayName: Apply the test annotation migrations
description: Applies the test annotation migrations.
applicability:
  anySource:
    - org.openrewrite.java.search.HasSourceSet:
        sourceSet: "test"
recipeList:
  - recipe.B
---
type: specs.openrewrite.org/v1beta/recipe
name: com.example.MigrateAnnotations
displayName: Applies annotation migrations
description: Applies annotation migrations.
recipeList:
  - com.example.MigrateMainAnnotation
  - com.example.MigrateTestAnnotation
```

Finally, you would run the `com.example.MigrateAnnotations` recipe now which would apply correctly to all source code as desired.

You can read more about applicability tests here in the documentation: https://docs.openrewrite.org/reference/yaml-format-reference
