### ISSUE TITLE
Rewrite Gradle's recipes don't work on a Kotlin monorepo with multi Gradle's project

### ISSUE THREAD

**Issue by shakhar** [openrewrite/rewrite-gradle-plugin#324]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v6.20.0
- Gradle plugin v6.20.0

## How are you running OpenRewrite?

I am using the Gradle plugin, and my project is a Kotlin-Spring based monorepo multi-module project.

root build.gradle.kts configuration:
```kotlin
plugin {
    id("org.openrewrite.rewrite") version "6.20.0"
}

rewrite {
    activeRecipe("com.fiverr.KoreV2")
}

rewrite {
    activeRecipe("com.fiverr.KoreV2")
}

dependencies {
    rewrite("org.openrewrite:rewrite-gradle")
    rewrite(platform("org.openrewrite.recipe:rewrite-recipe-bom:2.17.0"))
}
```

root rewrite.yml file:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.fiverr.KoreV2
recipeList:
   - org.openrewrite.gradle.ChangeDependencyGroupId:
        groupId: com.x.libs
        artifactId: graphql-client-core
        newGroupId: com.x.kore
```

## What is the smallest, simplest way to reproduce the problem?
Create a Kotlin monorepo with multi-module project, with the following structure:
```
apps >
  app1 >
      build.gradle.kts
  app2 >
      build.gradle.kts
libs >
  lib1 >
      build.gradle.kts
  lib2 >
      build.gradle.kts
build.gradle.kts
settings.gradle.kts
```
and run some Gradle dependency related recipes on this repo.

## What did you expect to see?
I expect it to change my dependency's groupId from `com.x.libs` to `com.x.kore`.

## What did you see instead?
"Applying recipes would make no changes. No report generated"
