### ISSUE TITLE
ChangeDependency recipe is not relocating dependencies defined in sub-modules

### ISSUE THREAD

**Issue by sihutch** [openrewrite/rewrite-gradle-plugin#334]
- OpenRewrite 8.5.32
- Maven/Gradle plugin latest.release

## How are you running OpenRewrite?

Gradle plugin
multi-module project

Can you share your configuration so that we can rule out any configuration issues? Sample project [here](https://github.com/sihutch/rewrite-subproject-test)

The sample project has a root project with no dependencies and a sub-module with a single dependency. 

```
dependencies {
    compileOnly "javax.servlet:javax.servlet-api:3.0.1"
}
```

The rewrite.yml file contains a recipe which should relocate this dependency to jakarta.servlet:akarta.servlet-api:6.1.0

```
type: specs.openrewrite.org/v1beta/recipe
name: com.si.ChangeDependencyExample
displayName: Change Gradle dependency example
recipeList:
  - org.openrewrite.gradle.ChangeDependency:
      oldGroupId: javax.servlet
      oldArtifactId: javax.servlet-api
      newGroupId: jakarta.servlet
      newArtifactId: jakarta.servlet-api
      newVersion: 6.1.0
```

When I execute the `rewriteRun` task against the sample project, no changes are made. However, if I copy 

```
dependencies {
    compileOnly "javax.servlet:javax.servlet-api:3.0.1"
}
```
into the root project, then running the recipe updates both the root and the sub-modules; the failure to update occurs only when the dependency is only defined in the sub-modules.

I created a test in [this PR ](https://github.com/openrewrite/rewrite/pull/4498), and it passed, so I am unsure where the problem lies. Is it possiblly with the plugin?
