### ISSUE TITLE
Unable to rewrite a multivalue application.yml file

### ISSUE THREAD

**Issue by k3vonk** [openrewrite/rewrite-gradle-plugin#337]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v2.4.2

## How are you running OpenRewrite?

IntelliJ plugin and running the play button on a openRewrite script.

I believe this adds the gradle plugin as part of the run processes.

## What is the smallest, simplest way to reproduce the problem?

```yml
spring:
  application:
    name: "Test"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.test.old.library.Something
```

## What did you expect to see?

```yml
spring:
  application:
    name: "Test"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.test.new.library.Something
```

## What did you see instead?

```yml
spring:
  application:
    name: "Test"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.test.old.library.Something
```

## What is the full stack trace of any errors you encountered?

No errors as nothing was detected for rewriting

## My recipe:

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.test.rewrite
displayName: Change YAML property example
recipeList:
  - org.openrewrite.yaml.ChangePropertyValue:
      propertyKey: spring.autoconfigure.exclude
      oldValue: com.test.old*
      newValue: com.test.new
      regex: true
      filePattern: src/test/resources/*.yml
```

I've tested this in a non multivalue property and it works but not for a multi value property.
